version: "2"
services:
  client:
    image: node:8.16-jessie
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/
    volumes:
      - ./Front:/client/
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - app-network
  api:
    image: node:8.16-jessie
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./Back:/api
      - /api/nodes_modules
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
      image: mongo
      restart: always
      container_name: mongodb
      volumes:
        - ./data-node:/data/db
      ports:
        - "27017:27017"
      command: mongod --noauth --smallfiles
      networks:
        - app-network
networks:
  app-network:
    driver: bridge