#!/bin/bash

ip=$(ifconfig | grep -Eo '10\.\d\.\d\.\d')

FrontServerLine=$(cat Front/.env | grep -Eo "^SERVER ?= ?(.*)$")
BackServerLine=$(cat Back/.env | grep -Eo "^SERVER ?= ?(.*)$")

sed -i "" "s|$FrontServerLine|SERVER=http://$ip|g" ./Front/.env
sed -i "" "s|$BackServerLine|SERVER=http://$ip|g" ./Back/.env
