#!/bin/bash

if command -v python3 &>/dev/null ;
then
    echo -e '\033[32mPython 3 is installed\033[0m'
else
    echo -e '\033[33mPython 3 is not installed\033[0m'
    brew install python3
fi

path=$(which python3)
sed -i "" "s%#!/usr/bin/env python3%#!$path%" deezpy.py
echo -e '\033[32mPyhton path set in ./deezpy.py\033[0m'

if pip3 list | grep -F requests &>/dev/null ;
then
	echo -e '\033[32mRequests is installed\033[0m'
else
	echo -e '\033[33mRequests is not installed\033[0m'
	pip3 install --user requests
fi

if pip3 list | grep -F cryptography &>/dev/null ;
then
	echo -e '\033[32mCryptography is installed\033[0m'
else
	echo -e '\033[33mCryptography is not installed\033[0m'
	pip3 install --user cryptography
fi

if pip3 list | grep -F mutagen &>/dev/null ;
then
	echo -e '\033[32mMutagen is installed\033[0m'
else
	echo -e '\033[33mMutagen is not installed\033[0m'
	pip3 install --user mutagen
fi

echo -e '\033[32mDependecies successfully installed.\033[0m'

cat banner

echo 'Last step to run the script :'
echo ' - add your userToken in ./deezpyrc (cf Readme)'
echo ' - ./deezpy.py'
echo ' - Enjoy :)'
